# Generated by Django 4.1.7 on 2023-03-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(default='cafe', max_length=150),
        ),
    ]
