# Generated by Django 4.1.7 on 2023-03-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_category_meta_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(max_length=150),
        ),
    ]
